version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - depguard
    - nolintlint
    - testpackage
    - varnamelen
  exclusions:
    rules:
    - path: internal/handlers # ignore because 'return c.JSON( is echo convention and wrapcheck hates it
      linters:
        - wrapcheck
      text: ".*"
    generated: lax
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
