version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - depguard # dont understand tbh, just doesnt let to import external packages in internal/*/*.go files
    - testpackage # forces to add _test prefix to package names in _test.go files, but how to test private functions then?
    - varnamelen # 'e' and 'c' are echo convetions for app and ctx var names, but this lint keeps complaining
    - wsl # deprecated since v2.2.0
  settings:
    tagliatelle:
      case:
        rules:
          yaml: snake
          json: snake
    tagalign:
      order:
          - json
          - form
  exclusions:
    rules:
    - path: services/auth/handler # ignore for wrapcheck because 'return c.JSON( is echo convention and wrapcheck hates it
      linters:
        - wrapcheck
      text: ".*"
    - path: services/management/handler
      linters:
        - wrapcheck
    - path: services/orders/handler
      linters:
        - wrapcheck
      text: ".*"
    - path: pkg/responses
      linters:
        - wrapcheck
      text: ".*"
    - path: services/orders/paymentproviders/stripe # there are a bunch of optional fields in stripe that exhauststruct is complaining about
      linters:
        - exhaustruct
      text: ".*"
    - path: services/management/storage/s3/s3
      linters:
        - exhaustruct
      text: ".*"
    - path: services/orders/services/payments_test
      linters:
        - exhaustruct
      text: ".*"
    - path: services/orders/services/orders_test
      linters:
        - exhaustruct
      text: ".*"
    - path: services/orders/handlers/orders_test
      linters:
        - dupl
      text: ".*"
    - path: services/orders/handlers/orders_test
      linters:
        - exhaustruct
    - path: services/management/middleware/auth_test
      linters:
        - exhaustruct
    generated: lax
formatters:
  enable:
    # - gci # not compatible with goimports and gofumpt, tries to change imports in different way.
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: lax
