run:
  max-issues-per-linter: 0
  max-same-issues: 0
  timeout: 5m
  tests: true

linters:
  enable-all: true
  disable:
    - wrapcheck
    - varnamelen
    - testpackage
    - depguard
    - gofumpt
    - gci # not compatible with goimports. Both try to change in different way
  # enable:
  #   - govet
  #   - errcheck
  #   - staticcheck
  #   - gosimple
  #   - unused
  #   - gofmt
  #   - goimports
  #   - ineffassign
  #   - misspell
  #   - unparam
  #   - stylecheck
  #   - gocritic
  #   - revive
  #   - gosec
  #   - prealloc
  #   - copyloopvar
issues:
  exclude-use-default: false

