root = "."
tmp_dir = "tmp"

[build]
  working_dir = "."
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  poll = true

[dev]
  cmd = "./tmp/main"

[log]
  time = false
