comment:
  layout: " header, diff, flags, files"
  behavior: new
  require_changes: false
  require_base: false
  require_head: false
  hide_project_coverage: false

coverage:
  status:
    patch: off 
