@baseUrl = http://localhost:42069/api/v1

### Singup manager
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "mngr-01@myemail.com",
    "password": "$pw11PWSLpw",
    "name": "sim",
    "lastname": "sim",
    "role": 1
}

### Login manager
# @name postLoginManager
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "mngr-01@myemail.com",
  "password": "$pw11PWSLpw"
}

@token = {{postLoginManager.response.body.data.token}}

### Create Restaurant
# @name postCreateRestaurant
POST {{baseUrl}}/restaurants
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Viskas Vienam KO",
  "address": "Nemenčinė Lauko g.",
  "currency": "gbp"
}

@restaurantId = {{postCreateRestaurant.response.body.data.id}}

### Update Restaurant
PATCH {{baseUrl}}/restaurants/{{restaurantId}}
Content-Type: application/json
Authorization: {{token}}

{
  "currency": "eur"
}

### Create Category 01
# @name postCreateCategory1
POST {{baseUrl}}/restaurants/{{restaurantId}}/menu/categories
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Kebabai",
    "description": "Lietuviška klasika"
}

@catId1 = {{postCreateCategory1.response.body.data.id}}

### Add Items
### Create Category 02
# @name postCreateCategory2
POST {{baseUrl}}/restaurants/{{restaurantId}}/menu/categories
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Pizzas",
    "description": "Lietuviška klasika iš Italijos"
}

@catId2 = {{postCreateCategory2.response.body.data.id}}

### Create Menu Item 01
# @name postCreateItem01
POST {{baseUrl}}/restaurants/{{restaurantId}}/menu/items
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Didelis Kebabas
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category_id"

{{catId1}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price_in_cents"

1199
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Saldus, didelis
------WebKitFormBoundary7MA4YWxkTrZu0gW--

@itemId1 = {{postCreateItem01.response.body.data.id}}

### Create Menu Item 02
# @name postCreateItem02
POST {{baseUrl}}/restaurants/{{restaurantId}}/menu/items
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Mažas Kebabas
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category_id"

{{catId1}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price_in_cents"

899
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Mažas, paprastas
------WebKitFormBoundary7MA4YWxkTrZu0gW--

@itemId2 = {{postCreateItem02.response.body.data.id}}

### Create Menu Item 03
# @name postCreateItem03
POST {{baseUrl}}/restaurants/{{restaurantId}}/menu/items
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Margarita
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category_id"

{{catId2}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price_in_cents"

1432
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Nežmoniškai daug sūrio
------WebKitFormBoundary7MA4YWxkTrZu0gW--

@itemId3 = {{postCreateItem03.response.body.data.id}}

### Create Menu Item 04
POST {{baseUrl}}/restaurants/{{restaurantId}}/menu/items
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Mafia
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category_id"

{{catId2}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price_in_cents"

1350
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Karšta, aštri, pikantiška
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### List menu items
GET {{baseUrl}}/restaurants/{{restaurantId}}/menu/items

Content-Type: application/json

### Add table 01
POST {{baseUrl}}/restaurants/{{restaurantId}}/tables
Authorization: {{token}}
Content-Type: application/json

{
  "name": "T01",
  "capacity": 4
}

### Add table 02
# @name postAddTable
POST {{baseUrl}}/restaurants/{{restaurantId}}/tables
Authorization: {{token}}
Content-Type: application/json

{
  "name": "T03",
  "capacity": 8
}

@tableId = {{postAddTable.response.body.data.id}}

### Get Current Table Order
# @name getCurrentTableOrder
GET {{baseUrl}}/orders/current?tableId={{tableId}}
Content-Type: application/json

@orderId = {{getCurrentTableOrder.response.body.data.id}}

### Add Item1 to Order
POST {{baseUrl}}/orders/{{orderId}}/items
Content-Type: application/json

{
  "item_id": "{{itemId1}}"
}

### Add Item2 to Order
# @name postAddItemToOrder
POST {{baseUrl}}/orders/{{orderId}}/items
Content-Type: application/json

{
  "item_id": "{{itemId2}}"
}

@orderItemId = {{postAddItemToOrder.response.body.data.items[0].id}}

### Delete Item from Order
DELETE {{baseUrl}}/orders/{{orderId}}/items
Content-Type: application/json

{
  "item_id": "8289501b-9fc6-43f7-b730-b01b861144ac"
}
